[amd64.amd64]
COMMON_FLAGS = "-O2 -pipe"

[amd64.x86_64]
COMMON_FLAGS = "-O2 -pipe"

[amd64.k8]
COMMON_FLAGS = "-O2 -march=k8 -pipe"
CPU_FLAGS_X86 = [ "mmx", "mmxext", "3dnow", "3dnowext", "sse", "sse2",]

[amd64.nocona]
COMMON_FLAGS = "-O2 -march=nocona -pipe"
CPU_FLAGS_X86 = [ "mmx", "mmxext", "sse", "sse2", "sse3",]

[amd64.core2]
COMMON_FLAGS = "-O2 -march=core2 -pipe"
CPU_FLAGS_X86 = [ "mmx", "mmxext", "sse", "sse2", "sse3", "ssse3",]

[amd64.k8-sse3]
COMMON_FLAGS = "-O2 -march=k8-sse3 -pipe"
CPU_FLAGS_X86 = [ "mmx", "mmxext", "3dnow", "3dnowext", "sse", "sse2", "sse3",]

[amd64.amdfam10]
COMMON_FLAGS = "-O2 -march=amdfam10 -pipe"
CPU_FLAGS_X86 = [ "mmx", "mmxext", "3dnow", "3dnowext", "sse", "sse2", "sse3", "sse4a",]

[amd64.x32]
COMMON_FLAGS = "-O2 -pipe"

