[riscv.riscv]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_multilib]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_lp64d]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_lp64d_musl]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-gentoo-linux-musl"

[riscv.rv64_lp64]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_lp64_musl]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-gentoo-linux-musl"

[riscv.rv32_ilp32d]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv32-unknown-linux-gnu"

[riscv.rv32_ilp32]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv32-unknown-linux-gnu"
